[I] Refactoring - Step 0
Insurlytech/zetapush-swift pull request #4
Opened 2019-04-19 13:57 UTC by anthonyGuiguen

2019-04-19 15:19 UTC, jgoas approved these changes

2019-04-19 16:08 UTC, StevenWatremez requested changes

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      publicToken = authentication["publicToken"] as? String ?? ""
check if you need parentheses like before.

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      let tempArray = subscriptionQueue.map({ $0 })
You can remove `.map({ $0 })`

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      DispatchQueue.main.asyncAfter(deadline: .now() + automaticReconnectionDelay) { [weak self] in
for this it is maybe useful to add `.now() + .seconds(automaticReconnectionDelay)` to really know that you are dealing with seconds.

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelperDelegate.swift
>  public protocol ClientHelperDelegate: NSObjectProtocol {
change `NSObjectProtocol` with `class`

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ZetaPushMacroService.swift
> +          let source = messageDict["source"] as? [String: Any] ?? [:]
manage this two lines with `if let source = messageDict["source"] as? [String: Any]`

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ZetaPushMacroService.swift
> +        let errorLocation = messageDict["location"] as? String ?? ""
This method return an error object, so it will be good to try to unwrap all values and if an unwrap fail we could return a default ZetaPushMacroError to ensure that the code will receive an error with a readable message 😄

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ZetaPushService.swift
> +        let errorSource = messageDict["source"] as? NSDictionary ?? [:]
This method return an error object, so it will be good to try to unwrap all values and if an unwrap fail we could return a default ZetaPushServiceError to ensure that the code will receive an error with a readable message 😄

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ZetaPushServiceDelegate.swift
>  public protocol ZetaPushServiceDelegate: NSObjectProtocol {
change `NSObjectProtocol` to `class`

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      cometdClient.connectHandshake(handshakeFields)
(Part 1) 
this part is similar to (Part 2) few line later so refact to create a centralized method for both.

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      self.cometdClient.connectHandshake(self.authentication!.getHandshakeFields(self))
(Part 2) 
this part is similar to (Part 1) few line before so refact to create a centralized method for both. 
In addition don't forget the `!`

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      guard let randomServer = servers[randomIndex] as? String else {
here we choose randomly a server. Maybe it will be good to use `servers.randomElement()` instead of `arc4random`

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      token = (authentication["token"] as? String) ?? ""
use `if let` here !

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      publicToken = authentication["publicToken"] as? String ?? ""
use `if let` here !

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +    userId = authentication["userId"] as? String ?? ""
here you have two options, use a guard and log if an error occurs, or use `if let` like before

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +    let authentication: NSDictionary = handshakeDict["authentication"] as? NSDictionary ?? [:]
use guard let here and log an error to be more precise when an error occurs.

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +      let handshakeFields = authentication?.getHandshakeFields(self) ?? [:]
add guard let here to check authentication and log errors

2019-04-19 16:08 UTC, StevenWatremez commented on ZetaPushSwift/ClientHelper.swift
> +        self.log.error (error!)
avoid `!`

2019-04-23 13:54 UTC, StevenWatremez approved these changes

2019-04-23 13:55 UTC, merged